name: backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter          # necessário porque o projeto usa provider e cupertino_icons

  # ───── servidor / backend ─────
  shelf: ^1.4.2           # manteve‑se a versão mais nova vista na branch main
  shelf_router: ^1.1.0
  http: ^1.1.0
  postgres: ^2.6.1        # upgrade em relação à 2.6.3 (exige pequenos ajustes no código)

  # ───── frontend / Flutter ─────
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0  #

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

